repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: mixed-line-ending
        args: ["--fix=lf"]
        description: Forces to replace line ending by the UNIX 'lf' character.
  - repo: local
    hooks:
      - id: format
        name: Format solidity code
        description: Format solidity code with `forge fmt`
        language: system
        entry: forge fmt
        exclude: "^lib/"
        pass_filenames: true
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier
        name: Format non solidity files with prettier
