dist: xenial
sudo: required
group: beta
language: node_js
services:
  - docker
# Build fails if cache is enabled unless caches are manually cleared from travis settings
# cache:
#   directories:
#     - node_modules
matrix:
  fast_finish: true
before_install:
  - docker pull maticnetwork/bor:develop
before_script:
  - npm install
script:
  - npm run template:process
  - npm run test:ci
