[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
no-match-contract = 'StakeManagerTestable'
optimizer = true
optimizer_runs = 200
via_ir = true
cache_path = 'forge-cache'
verbosity = 2
memory_limit = 40003554432
gas_limit = "18446744073709551615"

ffi = true
remappings = [
  "eth-gas-reporter/=node_modules/eth-gas-reporter/",
  "forge-std/=lib/forge-std/src/",
  "hardhat/=node_modules/hardhat/"
]
fs_permissions = [{ access = "read", path = "./scripts/"}, { access = "read", path = "./test/"},  { access = "read", path = "./out/"}]
auto_detect_solc = true

[invariant]
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

[profile.intense.fuzz]
runs = 10000
max_test_rejects = 999999

[fmt]
line_length = 120
number_underscore = "thousands"
multiline_func_header = "all"
wrap_comments = true
ignore = []

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
mainnet = "https://mainnet.infura.io/v3/${INFURA_TOKEN}"
# mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
sepolia = "https://sepolia.infura.io/v3/${INFURA_TOKEN}"
polygon_pos = "https://polygon-mainnet.infura.io/v3/${INFURA_TOKEN}"
mumbai = "https://polygon-mumbai.infura.io/v3/${INFURA_TOKEN}"
polygon_zkevm = "https://zkevm-rpc.com"
polygon_zkevm_testnet = "https://rpc.public.zkevm-test.net"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
polygon_pos = { key = "${POLYGONSCAN_API_KEY}" }
mumbai = { key = "${POLYGONSCAN_API_KEY}" }
polygon_zkevm = { key = "${POLYGONSCAN_ZKEVM_API_KEY}" }
polygon_zkevm_testnet = { key = "${POLYGONSCAN_ZKEVM_API_KEY}" }