// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import {Script, stdJson, console} from "forge-std/Script.sol";

// These imports get generated by npm run generate:interfaces
import {ValidatorShare} from "../../helpers/interfaces/ValidatorShare.generated.sol";
import {Registry} from "../../helpers/interfaces/Registry.generated.sol";

contract UpgradeValidatorShare_sPOL is Script {
    using stdJson for string;

    function run() public {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        string memory input = vm.readFile("scripts/deployers/input.json");
        string memory chainIdSlug = string(abi.encodePacked('["', vm.toString(block.chainid), '"]'));

        string memory artifactInput = vm.readFile("out/ValidatorShare.sol/ValidatorShare.json");
        bytes memory bytecode = vm.parseJsonBytes(artifactInput, ".bytecode.object");

        vm.startBroadcast(deployerPrivateKey);

        deployCode(ValidatorShare);

        // deploy new impl
        address newImpl;

        assembly {
            // create(value, offset, size)
            // value = 0 (no ETH), offset = bytecode data start, size = bytecode length
            newImpl := create(0, add(bytecode, 0x20), mload(bytecode))
        }

        console.log(newImpl);

        // Multisig: update address in registry
        /* Registry registry = Registry(input.readJson(chainIdSlug).readString("registry"));
        registry.setAddress("ValidatorShare", newImpl); */

        // Script: call _cacheDomainSeparatorV4 on existing validators

        vm.stopBroadcast();
    }
}
