// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import {Script, stdJson, console} from "forge-std/Script.sol";

// These imports get generated by npm run generate:interfaces
import {ValidatorShare} from "../../helpers/interfaces/ValidatorShare.generated.sol";
import {Registry} from "../../helpers/interfaces/Registry.generated.sol";

contract UpgradeValidatorShare_sPOL is Script {
    using stdJson for string;

    function run() public {
        vm.selectFork(vm.createFork(vm.rpcUrl("mainnet")));

        string memory input = vm.readFile("scripts/deployers/input.json");
        string memory chainIdSlug = string(abi.encodePacked('["', vm.toString(block.chainid), '"]'));

        // deploy new impl
        address newImpl = new ValidatorShare();

        // update address in registry
        Registry registry = Registry(input.readJson(chainIdSlug).readString("registry"));
        registry.setAddress("ValidatorShare", newImpl);
    }
}
