// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import {Script, stdJson, console} from "forge-std/Script.sol";

// These imports get generated by npm run generate:interfaces
import {Registry} from "../../scripts/helpers/interfaces/Registry.generated.sol";
import {Governance} from "../../scripts/helpers/interfaces/Governance.generated.sol";

contract UpgradeValidatorShare_sPOL is Script {
    using stdJson for string;

    function run() public {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        string memory input = vm.readFile("script/validatorShare-upgrade/input.json");
        string memory chainIdSlug = string(abi.encodePacked('["', vm.toString(block.chainid), '"]'));
        address governance = input.readAddress(string.concat(chainIdSlug, ".governance"));
        address gSafe = input.readAddress(string.concat(chainIdSlug, ".gSafe"));

        vm.startBroadcast(deployerPrivateKey);

        // deploy new impl
        address newImpl = vm.deployCode("ValidatorShare.sol");

        console.log(newImpl);

        // Multisig: update address in registry
        Registry registry = Registry(input.readAddress((string.concat(chainIdSlug, ".registry"))));

        bytes memory payload = abi.encodeCall(Governance.update, (address(registry), abi.encodeCall(registry.updateContractMap, (keccak256("validatorShare"), newImpl))));

        console.log("use Safe: ", gSafe);
        console.log("send to: ", governance);
        console.log("payload: ");
        console.logBytes(payload);

        vm.stopBroadcast();

        // run Script: call _cacheDomainSeparatorV4 on existing validators

        // for testing only
        vm.prank(gSafe);
        (
            bool success, /* bytes memory result */
        ) = governance.call(payload);
        require(success, "call failed");
        assert(registry.getValidatorShareAddress() == newImpl);
    }
}
